### ISSUE TITLE
Tags werden weiterhin als Liste dargestellt

### ISSUE THREAD

**Issue by powerriegel** [paulscode-de/bludit-tags_improved#1]
Hallo,

bei mir funzt die Tag Cloud von dir überhaupt nicht. Die Tags werden bei allen von mit getesteten Themes (devtheme, log, tagg) weiterhin als Liste dargestellt, nur die Schriftgröße ändert sich. Zudem sollte man Inline-Styles wirklich vermeiden, da sie das ganze HTML aufblähen. Ich würde hier mit Klassen arbeiten und dann auch mehrere Stufen anbieten, also nicht nur small, medium, large. , sondern 5-6 Abstufungen. 

Ich habe auf meiner Webseite 100te Tags und das sieht extrem übel aus so wie es ist. 

Gib mir bitte kurz Bescheid, ich bin selbst PHP Entwickler und kann auch einen Fork oder einen Pull Request machen.

**Comment by paulknulst** [comment]
Hallo,

danke fuer die Infos. Ich habe das Plugin nicht wirklich optimiert fuer andere Seiten. Ich benutze mein eigenes weiterentwickeltes Design: https://github.com/paulscode-de/bludit-paulish worauf es relativ vernuenftig aussieht. Siehe: https://blog.f1nalboss.de 

Dort funtkioniert das wunderbar. Falls ich Zeit habe werde ich auch noch das Admin Menu erweitern um die Einstellungen, die man machen kann. Z.b.
 - zu verwendene Klasse fuer die 5 unterschiedlichen Abstufungen
 - CSS was verwendet werden soll.
 - ab welcher nutzung was verwendet wird (z.b. ab 5 tags nehme klasse xy)

Sie koennen gerne das Plugin forken. Es ist super einfach zu veraendern und es anpassen fuer eine persoenliche Instanz. Ich selber werde das aber erst in naechster Zeit schaffen.

**Comment by paulknulst** [comment]
Sie koennen folgendes CSS verwenden, damit es so wie bei mir aussieht:
```
.plugin ul {
	list-style: none;
	padding: 0 0 0 20px;
}
ul.tags {
	list-style:none;
	padding-left:0;
	margin:0 0 3rem 0;
}
ul.tags li {
	display:inline-block;
	font-size:0.9rem;
	margin: 10px 0 0 2px;
}
ul.tags li a {
	background:rgba(0,0,0,.05);
	color:rgba(0,0,0,.6);
	border-radius:3px;
	padding:5px 10px;
}
ul.tags li a:hover {
	background:rgba(0,0,0,.07);
	text-decoration:none;
}
```

**Comment by powerriegel** [comment]
Danke, dann mache ich mir geschwind nen Fork und wenn ich zufrieden bin kann ich einen PR anbieten.

**Comment by powerriegel** [comment]
Hallo Paul, meine Version ist fertig. Übrigens ist in deiner Version eine Sicherheitslücke. Tags werden nicht escapt. Dadurch kann XSS in den Tags ausgeführt werden!

**Comment by paulknulst** [comment]
habe das problem gefixt und zusaetzlich das admin menu erweitert. sieht zwar nicht super aus, aber die funktionalitaet ist gegeben, danke fuer den hinweis
